#:kivy 1.11.1
<MyWidget>:
    orientation: 'vertical'
    Label:
        id:lb
        text: '0'
    BoxLayout:
        orientation:'horizontal'
        Button:
            id: btn
            text: 'Incrementar'
            background_color: [1,0,0,1]
            on_press: root.incrementar()
        Button:
            text:'Limpar'
            on_press: lb.text = '0'
            on_press: input.text = ''
    TextInput:
        id: input
        hint_text: 'Adicionar número'


        

